name: Sauce cypress githubactions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SAUCECTL_VERSION: 0.176.0
  BUILD_PREFIX: true

jobs:
    build-web-app:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/checkout@v2
          with:
            node-version: 12.x
        - name: Install Dependencies
          run: |
            npm install
        - name: Run build
          env:
            CI: false
          run: |
            npm run build


    test-web-app:
      runs-on: ubuntu-latest
      needs: build-web-app
      steps:
        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.7
        - name: Checkout Github App Code
          uses: actions/checout@v2
        - name: Install Dependencies
          run: |
            npm Install
        - name: Run Build
          env: 
            CI: false
          run: |
            npm run build
        - name: Download & Use Sauce Connect Tunnel
          run: |
            set -e
            curl -L -s https://saucelabs.com/downloads/sauce-connect/5.1.0/sauce-connect-5.1.0_linux.x86_64.tar.gz | sudo tar -xyz
            sc-5.1.0_linux/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i proxy-tunnel-$GITHUB_RUN_ID &
        - name: Install Saucectl
          run: |
            curl -L -s https://github.com/saucelabs/sauctl/releases/download/v$%7BSAUCECTL_VERSION%7D/saucectl_$%7BSAUCECTL_VERSION%7D_linux_64-bit.tar.gz%20%7C%20sudo%20tar%20-xyz%20-C%20/usr/bin/
        - name: Saucectl Run
          run: |
            cd build && python3 -m http.server 8000 &
            Saucectl run -c ./.sauce/config.yml --tunnel-id proxy-tunnel-$GITHUB_RUN_ID --test-env sauce




    
      
